# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Oh < Formula
  desc "OpenHub CLI — orchestrateur pour opencode"
  homepage "https://github.com/datichb/openhub"
  version "3.0.0"
  license "MIT"

  depends_on "beads" => :recommended
  depends_on "git"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/datichb/openhub/releases/download/v3.0.0/oh_darwin_amd64.tar.gz"
      sha256 "b14de8ffbc11264742249af1cbeb748cab7da0c38fc3bf8ee8bc407fee8de6f3"

      define_method(:install) do
        bin.install "oh"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/datichb/openhub/releases/download/v3.0.0/oh_darwin_arm64.tar.gz"
      sha256 "6b018b842e3cff738a9826763af3c7dc403d2ed488c40e8f5627ef132778fa50"

      define_method(:install) do
        bin.install "oh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/datichb/openhub/releases/download/v3.0.0/oh_linux_amd64.tar.gz"
      sha256 "349cb9b8400fb74ed75ba014a4c3c2677611caa0db343eb5b77860df3707ab1a"
      define_method(:install) do
        bin.install "oh"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/datichb/openhub/releases/download/v3.0.0/oh_linux_arm64.tar.gz"
      sha256 "649e9699dcf8455870c1da6a2ad36f2d67fa6ba03b6104e37ba4f85d6ca436fb"
      define_method(:install) do
        bin.install "oh"
      end
    end
  end

  test do
    system "#{bin}/oh", "version"
  end
end
