# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Openhub < Formula
  desc "OpenHub CLI — orchestrateur pour opencode"
  homepage "https://github.com/datichb/openhub"
  version "3.7.2"
  license "MIT"

  depends_on "beads" => :recommended
  depends_on "git"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/datichb/openhub/releases/download/v3.7.2/openhub_darwin_amd64.tar.gz"
      sha256 "f01a8b733396d546d6a2334202fd1a6e1ed024709a8ba01d67af1f9431133143"

      define_method(:install) do
        bin.install "oh"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/datichb/openhub/releases/download/v3.7.2/openhub_darwin_arm64.tar.gz"
      sha256 "d3e9b94de5e693203ea48632eca36b6e18f7727a6f82f2d425844cef76d07575"

      define_method(:install) do
        bin.install "oh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/datichb/openhub/releases/download/v3.7.2/openhub_linux_amd64.tar.gz"
      sha256 "051aa90e5888e6ce9e77208fa86708a52503fd187d5c787ddddd22f4666bd83e"
      define_method(:install) do
        bin.install "oh"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/datichb/openhub/releases/download/v3.7.2/openhub_linux_arm64.tar.gz"
      sha256 "c591a134973e753d892bfa288799d5190ec2793563dab4d3192cf4dea135d87d"
      define_method(:install) do
        bin.install "oh"
      end
    end
  end

  test do
    system "#{bin}/oh", "version"
  end
end
