# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Openhub < Formula
  desc "OpenHub CLI — orchestrateur pour opencode"
  homepage "https://github.com/datichb/openhub"
  version "4.1.0"
  license "MIT"

  depends_on "beads" => :recommended
  depends_on "git"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/datichb/openhub/releases/download/v4.1.0/openhub_darwin_amd64.tar.gz"
      sha256 "4aaa97f290d42907c5a9239129511621099bded9a7b3abbcec615f95c54ca161"

      define_method(:install) do
        bin.install "oh"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/datichb/openhub/releases/download/v4.1.0/openhub_darwin_arm64.tar.gz"
      sha256 "6cfafe823ee493d97d254354d7a6c29c31e76e7ab101c804c83d1399c36f65b1"

      define_method(:install) do
        bin.install "oh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/datichb/openhub/releases/download/v4.1.0/openhub_linux_amd64.tar.gz"
      sha256 "4e43b83037e430f6776139a586bb9e5d129259956766b9975570d575250cb412"
      define_method(:install) do
        bin.install "oh"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/datichb/openhub/releases/download/v4.1.0/openhub_linux_arm64.tar.gz"
      sha256 "a836122031d3399dd60e11b3524643ec1da4d75da2997fd87f5c3c4d34e71cda"
      define_method(:install) do
        bin.install "oh"
      end
    end
  end

  test do
    system "#{bin}/oh", "version"
  end
end
